[tool.poetry]
name = "tapen"
version = "0.2.0"
license = "GPL-3.0-or-later"
description = "Tapen - software for managing label printers"
authors = ["Dmitry Berezovsky"]
maintainers = ["Dmitry Berezovsky"]
repository = "https://github.com/corvis/tapen"
keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    # Who your project is intended for
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Home Automation",
    # License (should match "license" above)
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    # Python versions support
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
readme = "docs/pypi-description.md"
packages = [
    {include = "ptouch_py", from = "src"},
    {include = "tapen", from = "src"},
]
include = [
    "tapen/resources/*", "tapen/renderer/resources/*",
    "LICENSE", "README.md",
]

[tool.poetry.scripts]
tapen = "tapen.cli:default_entrypoint"
tpp = "tapen.cli:tpp_entrypoint"

[tool.poetry.dependencies]
python = ">=3.11,<3.16"
# PTouch
pyusb = "~1.3.1"
Pillow = ">=12.3.0"

# Tapen
cli-rack = { version = "~1.2.0", extras=["validation"] }
weasyprint="~=70.0"
pyyaml = ">=5.0.0"
appdirs = ">=1.4.4"
jinja2 = ">=3.0.0, <4.0.0"
PyMuPDF = ">=1.26.0"

[tool.poetry.group.dev.dependencies]
# Dev tools
ruff = ">=0.15.7"
licenseheaders = "~=0.8"
mypy = ">=1.0.1"
pre-commit = "~=4.6.2"
mistune = ">=3.0.0"
pyinstaller = "~=6.22.2"
commitizen = ">=3.16.0"

# Type checking
types-PyYAML = ">=5.0.0"
types-Pillow = ">=10.0.0"

[tool.commitizen]
version_provider = "poetry"
bump_version = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
pre_bump_hooks = []
version_files = [
    "src/tapen/__version__.py",
]

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [".*pyi"]

[tool.ruff.lint.isort]
known-third-party = []
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"**.pyi" = ["UP"]
"test_*.py" = ["D103", "D104", "D100", "D101", "D102", "D106"]
"__version__.py" = ["D104", "D100", "D101", "D102"]

[tool.ruff.lint]
extend-ignore = [
    "S101",  # Use of assert statement. We have a lot of asserts for mypy type checking.
    "S324", # We cannot ignore sha1 hash in codebase because it is used by box.com

    # Target to resolve:
    "S113", # Requests without timout. We need to fix this, but it is not a blocker.
        # D202 No blank lines allowed after function docstring
    "D202",
    # W504 line break after binary operator
    ##### DOCSTRINGS #####
    # Missing docstring in public module
    "D100",
    # Missing docstring in __init__
    "D107",
    # Missing docstring in magic method
    "D105",
    # Missing docstring in public package
    "D104",
    # Missing docstring in public nested class
    "D106",
    # One black line required before class docstring
    "D203",
    #`no-blank-line-before-class
    "D211",
    # Multi-line docstring summary should start at the second line
    "D212",
    # Multi-line docstring summary should start at the first line
    "D213",
    # Raw string in exception
    "EM101",
    # f-string in exception
    "EM102",
]
extend-select = ["S","E", "B", "A", "EM", "UP", "D", "C90"]

[tool.ruff.lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
python_version = "3.11"
show_error_codes = true
ignore_errors = false
warn_return_any = false
disallow_any_generics = false
pretty = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
exclude = ["test_.*\\.py$", ]

[[tool.mypy.overrides]]
module = ["examples"]
ignore_errors = true
follow_imports = "silent"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["weasyprint.*", "cli_rack_validation.*", "cli_rack.*", "usb.*", "appdirs.*", "fitz.*"]
ignore_missing_imports = true
follow_imports = "skip"
