CONF_NAME = "name"
CONF_URL = "url"
CONF_LIBRARIES = "libraries"

C_DEFAULT = "default"
C_REQUIRED = "required"
C_VALIDATOR = "validator"
C_DESCRIPTION = "description"
C_ARGS = "args"
C_NAME = "name"

MF_META_SECTION = "template"
MF_NAME = "name"
MF_DESCRIPTION = "description"
MF_AUTHOR = "author"
MF_LICENSE = "license"
MF_PARAMS = "params"

MF_LAYOUT = "layout"
MF_TEMPLATE = "template"
MF_CSS = "css"